logging:
  level:
    org.zalando.logbook: TRACE
spring:
  datasource:
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true # Включает веб-интерфейс H2 Console
      path: /h2-console # URL для доступа
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true # Показывать SQL в логах (для отладки)
    properties:
      hibernate.format_sql: true # Красивое форматирование SQL


  sql:
    init:
      mode: always