logging:
  level:
    org.zalando.logbook: TRACE
spring:
  datasource:
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
#    url: jdbc:h2:mem:filmorate_db;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true # Включает веб-интерфейс H2 Console
      path: /h2-console # URL для доступа
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true # Показывать SQL в логах (для отладки)
    properties:
      hibernate.format_sql: true # Красивое форматирование SQL
#    open-in-view: false

  sql:
    init:
      mode: always  # Всегда выполнять инициализацию
      platform: h2  # Указываем платформу (не обязательно)
      encoding: UTF-8  # Кодировка скриптов
      separator: ;    # Разделитель SQL-команд
      continue-on-error: false  # Прекращать при ошибке